export Avaliacoes from './Avaliacoes'
export Experiencia from './Experiencia'
export Funcoes from './Funcoes'
export Historico from './Historico'
export Info from './Info'
export Portfolio from './Portfolio'
export Seguidores from './Seguidores'
