export const ACCENT = '#e36a55';
// export const AREA_TEXTO = '#61c785'
// export const AREA_IMAGEM = '#8c4f9d'
// export const AREA_CENA = '#33b2bc'
// export const AREA_AUDIO = '#fbae18'
// export const AREA_PRODUCAO = '#e36954'

export const BLACK = '#292828'
export const BLACK_LIGHT = '#444444'
export const LIGHT_1 = '#fafafa'
export const LIGHT_MEDIUM = '#e5e5e5'
export const LIGHT_DARK = '#b5b5bb'
export const PRIMARY = '#e36a55'
export const AREA_TEXTO = '#60c884'
export const AREA_IMAGEM = '#8b4e9f'
export const AREA_AUDIO = '#fbaf19'
export const AREA_CENA = '#2aafb9'
